### ISSUE TITLE
Error in the SPARQL Conversion

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#284]
```python
from owlapy.model import OWLClass, IRI, OWLObjectIntersectionOf, OWLObjectUnionOf
from owlapy.owl2sparql.converter import Owl2SparqlConverter

namespace = "http://www.benchmark.org/family#"
father = OWLClass(IRI.create(namespace, 'Father'))
cnv = Owl2SparqlConverter()
root_var = "?x"
ce_complex=OWLObjectUnionOf((OWLObjectIntersectionOf((father, father)),
                                               OWLObjectIntersectionOf((father, father))))
ce_complex=OWLObjectIntersectionOf((ce_complex, ce_complex))
print(cnv.as_query(root_var, ce_complex))

```

```bash
Traceback (most recent call last):
  File "/home/demir/Desktop/Softwares/Ontolearn/concept_gen.py", line 14, in <module>
    print(cnv.as_query(root_var, ce_complex))
  File "/home/demir/Desktop/Softwares/Ontolearn/owlapy/owl2sparql/converter.py", line 571, in as_query
    tp = self.convert(root_variable, ce, named_individuals)
  File "/home/demir/Desktop/Softwares/Ontolearn/owlapy/owl2sparql/converter.py", line 107, in convert
    self.process(ce)
  File "/home/demir/anaconda3/envs/nrw/lib/python3.9/functools.py", line 938, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/demir/Desktop/Softwares/Ontolearn/owlapy/owl2sparql/converter.py", line 221, in _
    self.append(f"FILTER ( {v0} != {v1} )")
  File "/home/demir/anaconda3/envs/nrw/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/demir/Desktop/Softwares/Ontolearn/owlapy/owl2sparql/converter.py", line 164, in intersection
    del self._intersection[self.modal_depth]
KeyError: 1
```

Python 3.9.17
'0.6.0.dev'

**Comment by Demirrr** [comment]
@nkaralis @alkidbaci any of you have a fix for ths ?

**Comment by Demirrr** [comment]
This issue is a blocked for few our other works

**Comment by Demirrr** [comment]
https://github.com/dice-group/Ontolearn/pull/283 fixed this issue. Thanks to @nkaralis 🙂
