### ISSUE TITLE
"KeyError: 'pos' Exception in ASGI Application"

### ISSUE THREAD

**Issue by farshad68** [dice-group/Ontolearn#383]
**Description:**
When making a request to the endpoint `http://[IP]:8000/cel` using the Python Requests library, an unexpected internal server error occurs, resulting in a KeyError: 'pos' exception. This issue arises despite providing the necessary headers and JSON data in the request.

**Steps to Reproduce:**
1. Use the Python Requests library to send a GET request to the endpoint `http://[IP]:8000/cel`.
2. Include the following headers in the request:
    ```
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    ```
3. Provide the JSON data with the request, containing positive and negative inputs along with the model and path to embeddings CSV file:
    ```
    data = {
        "positives": ["https://www.wikidata.org/wiki/Q9401", "https://www.wikidata.org/wiki/Q3895"], 
        "negatives": ["https://www.wikidata.org/wiki/Q234021"],
        "model": "Drill",
        "path_embeddings": [locationOfCSVFile]
    }
    ```
4. Observe the response for any internal server errors or exceptions.

**Expected Behavior:**
The endpoint `http://[IP]:8000/cel` should handle the request gracefully, processing the provided JSON data without encountering any internal server errors.

**Actual Behavior:**
The endpoint throws a KeyError: 'pos' exception, indicating that the 'pos' key is missing in the JSON data provided with the request.

LOG is 
```
ontolearn-webservice --path_knowledge_base /home/shared/app2/49a58cfe-0194-4820-9b6a-82c1bc657b51/5e332ca0-c875-4e3b-b143-47cabc6df1d4/857724241.owl
INFO:     Started server process [16]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
No pre-trained model...
No training
No saving..
No saving..
INFO:     172.19.0.4:43534 - "GET /cel HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/[applications.py](http://applications.py/)", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[applications.py](http://applications.py/)", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[errors.py](http://errors.py/)", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[errors.py](http://errors.py/)", line 164, in __call__
    await [self.app](http://self.app/)(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[exceptions.py](http://exceptions.py/)", line 65, in __call__
    await wrap_app_handling_exceptions([self.app](http://self.app/), conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 297, in handle
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/[routing.py](http://routing.py/)", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/[routing.py](http://routing.py/)", line 191, in run_endpoint_function
    return await [dependant.call](http://dependant.call/)(**values)
  File "/Ontolearn/ontolearn/scripts/[run.py](http://run.py/)", line 100, in cel
    positives = {OWLNamedIndividual(IRI.create(i)) for i in data['pos']}
KeyError: 'pos'
No pre-trained model...
No loading because embeddings not provided
INFO:     172.19.0.4:43544 - "GET /cel HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/[applications.py](http://applications.py/)", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[applications.py](http://applications.py/)", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[errors.py](http://errors.py/)", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[errors.py](http://errors.py/)", line 164, in __call__
    await [self.app](http://self.app/)(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/[exceptions.py](http://exceptions.py/)", line 65, in __call__
    await wrap_app_handling_exceptions([self.app](http://self.app/), conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 297, in handle
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/[routing.py](http://routing.py/)", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/[routing.py](http://routing.py/)", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/[routing.py](http://routing.py/)", line 191, in run_endpoint_function
    return await [dependant.call](http://dependant.call/)(**values)
  File "/Ontolearn/ontolearn/scripts/[run.py](http://run.py/)", line 100, in cel
    positives = {OWLNamedIndividual(IRI.create(i)) for i in data['pos']}
KeyError: 'pos'
```

**Comment by Demirrr** [comment]
You are sending wrong type. Please take a look at the readme. It should be pos, not positive as you are sending

**Comment by Demirrr** [comment]
curl -X 'GET' 'http://0.0.0.0:8000/cel' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"pos":["http://www.benchmark.org/family#F10F175"], "neg":["http://www.benchmark.org/family#F10F177"], "model":"Drill"}'

Not positive but pos

**Comment by farshad68** [comment]
thank you I will test and inform again :)

**Comment by Demirrr** [comment]
No no. Thank you for testing our service 🙂
