### ISSUE TITLE
Error 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by farshad68** [dice-group/Ontolearn#453]
We use the Ontolern at this commit "c0bb717c4d49d4f11e37f85f27cbe2dc4fdeebf4" 
When I use this dataset "https://files.dice-research.org/projects/ENEXA/FirstDemoFiles/wikidata5M.nt" and load it to TENTRIS , then pass the triple store API to the application  this exception happened 
```
ontolearn-webservice --endpoint_triple_store http://10.1.194.119:9080/sparql
INFO:     Started server process [16]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
######### CEL Arguments ###############
Knowledgebase/Triplestore:<ontolearn.triple_store.TripleStore object at 0x7f828d5dc970>

Input data:{'pos': ['http://www.wikidata.org/entity/Q3895', 'http://www.wikidata.org/entity/Q180855'], 'neg': ['http://www.wikidata.org/entity/Q483915', 'http://www.wikidata.org/entity/Q1359568', 'http://www.wikidata.org/entity/Q169167', 'http://www.wikidata.org/entity/Q192334', 'http://www.wikidata.org/entity/Q695087', 'http://www.wikidata.org/entity/Q20165', 'http://www.wikidata.org/entity/Q2087161'], 'model': 'Drill', 'max_runtime': 180, 'iter_bound': 2, 'path_to_pretrained_drill': 'pretrained_drill', 'path_embeddings': '/enexa/app3/2b3864f6-550a-46b8-aa26-b0476425f0de/Keci_embeddings_group1-data.csv'}

######### CEL Arguments ###############

Reading Embeddings...	(2462, 32)
Training over learning problems: 0it [00:00, ?it/s]
INFO:     10.1.194.75:41778 - "GET /cel HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Ontolearn/ontolearn/scripts/run.py", line 96, in cel
    owl_learner = get_learner(data)
  File "/Ontolearn/ontolearn/scripts/run.py", line 80, in get_learner
    return get_drill(data)
  File "/Ontolearn/ontolearn/scripts/run.py", line 67, in get_drill
    drill.train(num_of_target_concepts=data.get("num_of_target_concepts", 1),
  File "/Ontolearn/ontolearn/learners/drill.py", line 224, in train
    for (target_owl_ce, positives, negatives) in training_data:
  File "/usr/local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable


```

by changing the data to smaller version (https://files.dice-research.org/projects/ENEXA/SecondDemoFiles/group1-data.nt) exception did not happened

**Comment by Demirrr** [comment]
Thank you. I will take a look at it 👍

**Comment by Demirrr** [comment]
If a training dataset is empty, we provide a user an explanation (instead of plain assertion error).
Completed in https://github.com/dice-group/Ontolearn/pull/455
