### ISSUE TITLE
Main.py Broken

### ISSUE THREAD

**Issue by heindorf** [dice-group/Ontolearn#476]
The command `python main.py` yields

```
Traceback (most recent call last):
  File "/home/heindorf/git/Ontolearn/main.py", line 25, in <module>
    from ontolearn.executor import execute
  File "/home/heindorf/git/Ontolearn/ontolearn/executor.py", line 40, in <module>
    from ontolearn.concept_learner import CELOE, OCEL, EvoLearner, NCES
ImportError: cannot import name 'OCEL' from 'ontolearn.concept_learner' (/home/heindorf/git/Ontolearn/ontolearn/concept_learner.py)
```

**Comment by Demirrr** [comment]
Please use main branch until this issue is fixed

**Comment by Demirrr** [comment]
fixed in #478
